CREATE DATABASE IF NOT EXISTS `tw_nfe`;
-- SELECIONANDO UMA BASE DE DADOS
USE tw_nfe;

-- CRIANDO UMA TABELA
CREATE TABLE IF NOT EXISTS cli_clientes (
    cli_id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    -- cli_id SERIAL PRIMARY KEY,
    cli_nome VARCHAR(50) NOT NULL,
    cli_data_nascimento DATE,
    cli_logradouro VARCHAR(60) NOT NULL
);

ALTER TABLE cli_clientes 
ADD COLUMN cli_cpf CHAR(15) NOT NULL DEFAULT'000.000.000-00'

ALTER TABLE cli_clientes 
ADD COLUMN cli_cpf2 CHAR(15) NOT NULL DEFAULT'000.000.000-00' AFTER cli_sexo